site_name: Mason's News Aggregator
site_url: https://sleepy-tereshkova-ede477.netlify.app/
site_author: Mason McElvain
site_description: 'CSC 305 Final Analysis'

theme:
  name: null
  custom_dir: 'cinder'

nav:
  - Visitor Pattern: visitor.md
  - Composite Pattern: composite.md
  - Decorator Pattern: decorator.md
